### ISSUE TITLE
Unexpected expression type in QuerySimulation

### ISSUE THREAD

**Issue by xPaw** [staabm/phpstan-dba#276]
```php
$queries = [ 'SELECT 1' ];

foreach( $queries as $test )
{
	$test = $pdo->prepare( $test ); // reusing variable
	$test->execute();
}
```

However this doesn't crash:
```php
$test = 'SELECT 1';
$test = Container::Database()->prepare( $test );
$test->execute();
```

Something about the loop makes it confuse the type. Obviously reusing the variable isn't a good idea (and I fixed it in my code), but it probably shouldn't crash.

```
Uncaught staabm\PHPStanDba\DbaException: Unexpected expression type [snip] of class PHPStan\Type\Generic\GenericObjectType in phpstan-dba\src\QueryReflection\QuerySimulation.php:117
#0 phpstan-dba\src\QueryReflection\QueryReflection.php(189): staabm\PHPStanDba\QueryReflection\QuerySimulation::simulateParamValueType(Object(PHPStan\Type\Generic\GenericObjectType), false)
#1 phpstan-dba\src\QueryReflection\QueryReflection.php(165): staabm\PHPStanDba\QueryReflection\QueryReflection->resolveQueryStringExpr(Object(PhpParser\Node\Expr\Variable), Object(PHPStan\Analyser\MutatingScope))
#2 phpstan-dba\src\QueryReflection\QueryReflection.php(137): staabm\PHPStanDba\QueryReflection\QueryReflection->resolveQueryExpr(Object(PhpParser\Node\Expr\Variable), Object(PHPStan\Analyser\MutatingScope))
```

**Comment by staabm** [comment]
thx for reporting. does your real world example really contains a array of literal strings above the loop?
or will it be more complex then that?

I am asking, because we might fix the case you reported, while not fixing your actual problem in case the above example is not realistic

**Comment by xPaw** [comment]
> does your real world example really contains a array of literal strings above the loop?

I did have an array of queries to run, yeah.

**Comment by staabm** [comment]
I think this could be fixed by resolveing the query expression type and look whether it contains a constant steing.

if so, return immediately in https://github.com/staabm/phpstan-dba/blob/6bd6e84331c6e15d76868e14444ed20c2aab06b9/src/QueryReflection/QueryReflection.php#L148

**Comment by staabm** [comment]
Thinking more about it.. a example with more then 1 query is more obvious.

Within the loop the result of the query function would be a union of all possible result types, not just a single one as the initial example might suggest
