### ISSUE TITLE
Doctrine types support 

### ISSUE THREAD

**Issue by Seldaek** [staabm/phpstan-dba#278]
Doctrine supports extra types which can be bound as parameters so it'd be nice if this was supported:

[Doctrine\DBAL\Types\Types](https://github.com/doctrine/dbal/blob/3.3.x/src/Types/Types.php)

One example usage:

```
        $sql = 'UPDATE foo SET last_dt=:last_dt';

        $paramValues = [
            'last_dt' => $lastUsed,
        ];
        $paramTypes = [
            'last_dt' => \Doctrine\DBAL\Types\Type::DATETIME,
        ];

        $updated = $connection->executeUpdate($sql, $paramValues, $paramTypes);
```

Currently this yields:
```
     Internal error: Internal error: Unexpected expression type DateTime of class PHPStan\Type\ObjectType in file /src/Foo.php

     Post the following stack trace to https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md:
     #0 /vendor/staabm/phpstan-dba/src/QueryReflection/QueryReflection.php(258): staabm\PHPStanDba\QueryReflection\QuerySimulation::simulateParamValueType()
     #1 /vendor/staabm/phpstan-dba/src/QueryReflection/QueryReflection.php(223): staabm\PHPStanDba\QueryReflection\QueryReflection->resolveConstantArray()
     #2 /vendor/staabm/phpstan-dba/src/Rules/SyntaxErrorInPreparedStatementMethodRule.php(110): staabm\PHPStanDba\QueryReflection\QueryReflection->resolveParameters()
     #3 /vendor/staabm/phpstan-dba/src/Rules/SyntaxErrorInPreparedStatementMethodRule.php(82): staabm\PHPStanDba\Rules\SyntaxErrorInPreparedStatementMethodRule->checkErrors()
     #4 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(102): staabm\PHPStanDba\Rules\SyntaxErrorInPreparedStatementMethodRule->processNode()
```

**Comment by stof** [comment]
Note that you might rely on the phpstan-doctrine tooling to know the conversion between the PHP type and the database type performed by those DBAL types instead of re-inventing your own logic there.
A project using doctrine is likely to have this extension.
