### ISSUE TITLE
Regression in latest release

### ISSUE THREAD

**Issue by Seldaek** [staabm/phpstan-dba#452]
Somehow updating from 0.2.48 to 0.2.49 crashes phpstan with:

```
Internal error: Internal error: Unexpected expression type XXX of class PHPStan\Type\ObjectType in file ....

Post the following stack trace to https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md:
#0 /vendor/staabm/phpstan-dba/src/QueryReflection/QueryReflection.php(243):
staabm\PHPStanDba\QueryReflection\QuerySimulation::simulateParamValueType()
#1 /vendor/staabm/phpstan-dba/src/QueryReflection/QueryReflection.php(180):
staabm\PHPStanDba\QueryReflection\QueryReflection->resolveQueryStringExpr()
#2 /vendor/staabm/phpstan-dba/src/QueryReflection/QueryReflection.php(146):
staabm\PHPStanDba\QueryReflection\QueryReflection->resolveQueryExpr()
#3 /vendor/staabm/phpstan-dba/src/Rules/SyntaxErrorInQueryMethodRule.php(83):
staabm\PHPStanDba\QueryReflection\QueryReflection->resolveQueryStrings()
#4 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(106):
staabm\PHPStanDba\Rules\SyntaxErrorInQueryMethodRule->processNode()
#5 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.php(95):
PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}()
#6 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(502):
PHPStan\Node\ClassStatementsGatherer->__invoke()
#7 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2459):
PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}()
#8 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1451):
PHPStan\Analyser\NodeScopeResolver->callNodeCallbackWithExpression()
#9 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(554):
PHPStan\Analyser\NodeScopeResolver->processExprNode()
#10 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(356):
PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#11 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(517):
PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#12 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(356):
PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#13 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(595):
PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#14 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(356):
PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#15 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(567):
PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#16 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(326):
PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#17 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(175):
PHPStan\Analyser\NodeScopeResolver->processNodes()
#18 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(147): PHPStan\Analyser\FileAnalyser->analyseFile()
#19 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
PHPStan\Command\WorkerCommand->PHPStan\Command\{closure}()
#20 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/clue/ndjson-react/src/Decoder.php(110):
#21 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
_PHPStan_71ced81c9\Clue\React\NDJson\Decoder->handleData()
#22 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/Util.php(62):
_PHPStan_71ced81c9\Evenement\EventEmitter->emit()
#23 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
_PHPStan_71ced81c9\React\Stream\Util::_PHPStan_71ced81c9\React\Stream\{closure}()
#24 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/DuplexResourceStream.php(154):
_PHPStan_71ced81c9\Evenement\EventEmitter->emit()
#25 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(201):
_PHPStan_71ced81c9\React\Stream\DuplexResourceStream->handleData()
#26 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(173):
_PHPStan_71ced81c9\React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#27 phar:///vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(107):
_PHPStan_71ced81c9\React\EventLoop\StreamSelectLoop->run()
#28 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259):
PHPStan\Command\WorkerCommand->execute()
#29 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(868):
_PHPStan_71ced81c9\Symfony\Component\Console\Command\Command->run()
#30 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(259):
_PHPStan_71ced81c9\Symfony\Component\Console\Application->doRunCommand()
#31 phar:///vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157):
_PHPStan_71ced81c9\Symfony\Component\Console\Application->doRun()
#32 phar:///vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(124): _PHPStan_71ced81c9\Symfony\Component\Console\Application->run()
#33 phar:///vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(125): _PHPStan_71ced81c9\{closure}()
#34 /vendor/phpstan/phpstan/phpstan(8): require('...')
#35 /bin/phpstan(120): include('...')
```

I hope that's enough info..

**Comment by staabm** [comment]
thx for reporting. should be fixed in the newly tagged release

**Comment by Seldaek** [comment]
Ah I see, it required phpstan 1.9dev? I'm up to date but not *that* bleeding edge 😄
